#ifndef BOOTLOADER_H_
#define BOOTLOADER_H_

#define BOOT_SECTOR_START      0
#define BOOT_SECTOR_END        7
#define BOOT_ADDRESS_OFFSET    0x0000

#define RUNTIME_SECTOR_START   8
#define RUNTIME_SECTOR_END     21
#define RUNTIME_ADDRESS_OFFSET 0x8000

#define UPDATE_SECTOR_START    22
#define UPDATE_SECTOR_END      29
#define UPDATE_ADDRESS_OFFSET  0x40000

#define BOOTLOADER_MAGIC_WORD 0xAAAAAAAA

void update_firmware( void );

#endif
